---
- name: Create an EC2 key
  local_action:
    module: ec2_key
    region: "{{ ec2_region }}"
    name: "{{ ssh_key_name }}"
  register: ec2_key

- name: Save the private key
  copy: content="{{ ec2_key.key.private_key }}" dest="{{ ssh_key_location }}" mode=0400
  when: ec2_key.changed
