---
- name: List existing clusters
  command: "aws emr list-clusters --active --output json"
  register: existing_emrs_res
- set_fact: existing_emrs="{{ existing_emrs_res.stdout | from_json }}"
- block:
  - name: Create tmp directory
    shell: mktemp -d /tmp/emr.XXXXXX
    register: emr_conf_tmp_dir
  - name: Populate EMR JSON configs with values
    template:
      src: "{{ role_path }}/templates/{{ item }}"
      dest: "{{ emr_conf_tmp_dir.stdout }}/{{ item }}"
    with_items:
    - "{{ emr_bootstrap_actions_file }}"
  - name: Create EMR cluster
    command: >
      aws emr create-cluster --name "{{ emr_cluster_name }}"
      --enable-debugging
      --log-uri {{ emr_cluster_log_url }}
      --release-label {{ emr_release_label }}
      --applications {{ emr_applications_config }}
      --ec2-attributes {{ emr_ec2_attributes_config }}
      --bootstrap-action file://{{ emr_conf_tmp_dir.stdout }}/{{ emr_bootstrap_actions_file }}
      --configurations {{ emr_configurations_url }}
      --instance-groups {{ emr_instance_groups_config }}
      --use-default-roles
      --output json
  - name: Cleanup temp data
    file: path={{ emr_conf_tmp_dir.stdout }} state=absent
  when: existing_emrs.Clusters | length == 0
