---

- name: Create S3 bucket
  s3: bucket={{ s3_bucket_name }} mode=create

- name: Create tmp directory
  shell: mktemp -d /tmp/riksdagens_data.XXXXXX
  register: tmp_dir

- name: Download dataset catalogue
  get_url: url={{ riksdagens_dataset_catalogue }} dest={{ tmp_dir.stdout }}
  register: catalogue

- name: Extract dataset URLs
  shell: grep -io '{{ riksdagens_dataset_pattern }}' {{ catalogue.dest }} | sort -u
  register: dataset_urls

- name: Download datasets
  get_url: url={{ item | regex_replace(' ', '%20') }} dest={{ tmp_dir.stdout }}
  with_items: "{{ dataset_urls.stdout_lines }}"

- name: Upload datasets to S3
  s3:
    bucket: "{{ s3_bucket_name }}"
    mode: put
    object: "{{ riksdagens_dataset_s3_key_prefix }}/{{ item | basename }}"
    src: "{{ item }}"
  with_fileglob: "{{ tmp_dir.stdout }}/*.sql.zip"

- name: Cleanup temp data
  file: path={{ tmp_dir.stdout }} state=absent
