---

- name: Create an EC2 bastion node
  local_action:
    module: ec2
    region: "{{ ec2_region }}"
    key_name: "{{ ec2_key_name }}"
    group: "{{ ec2_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami_id }}"
    wait: yes
    instance_tags:
      Environment: "{{ ec2_tag_Environment }}"
