---

- name: Create an EC2 bastion node
  local_action:
    module: ec2
    region: "{{ ec2_region }}"
    key_name: "{{ ec2_key_name }}"
    group: "{{ ec2_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami_id }}"
    wait: yes
    instance_tags:
      Environment: "{{ ec2_tag_Environment }}"

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
