---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - trusted_sg
  - { ec2_ami: ami-c3be3fb0, role: jupyter_ec2, ec2_instance_type: t2.medium }
  #- { role: jupyter_ec2, ec2_instance_type: c4.8xlarge, ec2_spot_price: 0.4 }
  tags:
  - infrastructure

- hosts: tag_Name_jupyter
  roles:
  - os_base
  - jupyter
  tags:
  - provisioning

- hosts: tag_Name_jupyter
  roles:
  - jupyter_client
  tags:
  - client
