---
- hosts: tag_Name_bastion
  gather_facts: no
  roles:
  - ansible_manager

#- hosts: rds
- hosts: tag_Name_bastion
  gather_facts: no
  roles:
  - riksdagens_database

#- hosts: localhost
#  connection: local
#  gather_facts: no
#  roles:
#  - riksdagens_data_to_s3
#  - role: shell_data_pipeline
#    pipeline_name: riksdagens_data_s3_to_rds
#    pipeline_id: "{{ pipeline_name }}"
#    input_data_s3_path: s3://datawithoutborders/data/tmp
#    output_data_s3_path: s3://datawithoutborders/tmp/riksdagen
#    transformation_shell_cmd: sudo yum install -y postgresql && unzip  -p ${INPUT1_STAGING_DIR}/* | PGPASSWORD=riksdagen psql -U riksdagen

# echo "SELECT 1" | PGPASSWORD=top_secret psql -U ChosenOne -h vault13.ceoyhimtb9ex.eu-west-1.rds.amazonaws.com riksdagen