---
- hosts: tag_Name_bastion
  gather_facts: no
  roles:
  - ansible_manager

- hosts: rds
  gather_facts: no
  roles:
  - riksdagens_database

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - riksdagens_data_to_s3