---

- name: RDS security group
  local_action:
    module: ec2_group
    name: "{{ rds_security_group_name }}"
    description: RDS server security group
    region: "{{ ec2_region }}"
    state: present
    rules:
    - proto: tcp
      from_port: 5432
      to_port: 5432
      group_name: rds_client_sg
      group_desc: RDS client security group
  register: rds_sg
