---
emr_cluster_name: my-emr-cluster
s3_bucket_name: datawithoutborders
sqoop_s3_dir: app/sqoop
s3_dest_url: "s3://{{ s3_bucket_name }}/{{ sqoop_s3_dir }}"
sqoop_dist_name: sqoop-1.4.6.bin__hadoop-2.0.4-alpha.tar.gz
sqoop_dist_url: "http://apache.mirrors.spacedump.net/sqoop/1.4.6/{{ sqoop_dist_name }}"
sqoop_install_script_name: install_sqoop.sh
pg_jdbc_dist_name: postgresql-9.4.1207.jre7.jar
pg_jdbc_dist_url: "https://jdbc.postgresql.org/download/{{ pg_jdbc_dist_name }}"
